<?php
$pageTitle = "About | Tryallium";
$pageDescription = "Discover unique creative projects and exercises on our responsive website. Enhance your skills with our graphics design and quote generators.";
$pageKeywords = "prompt generator, creative exercises, training for designers and writers, graphics design assignment generator, quote generator, ChatGPT";
$pageAuthor = "Joen";
$pageName = "about";
include("../includes/header.php");
?>

<section>
      <h2>Introduction</h2>
      <p>
        Welcome to our website, which was created using ChatGPT. My name is Joen,
        and I'm a regular guy with limited coding knowledge. The idea to use ChatGPT to create
        this website came from my desire to build something unique and functional without
        writing any code myself. The result is a website that offers several projects and features
        that can be useful for creative professionals and others.
      </p>
    </section>
    <section>
      <h2>Projects and Features</h2>
      <p>
        Our website offers several projects and features, including a graphics design
        assignment generator and a quote generator that uses images from the Inspirobot API.
        We also have a little game where you guess the number the website is thinking of,
        with hints given to help you along the way. Additionally, the website is filled with
        humor, easter-eggs, and clever writing, all generated by ChatGPT.
      </p>
    </section>
    <section>
    <h2>Website Structure</h2>
    <p>
      The website is written in HTML and later converted to PHP for improved performance
      and security. The website is designed to be responsive and work on mobile devices,
      and we've worked hard to ensure that the website has great SEO and is easy to find
      on search engines. We've even created a <a href="https://github.com/joenb33/Tryallium">Github profile</a> where you can view all of the
      raw code that was generated by ChatGPT.
    </p>
  </section>
    <section>
      <h2>Conclusion</h2>
      <p>
        We hope you enjoy our website and find it useful for your creative projects or just
        for fun. While ChatGPT generated the code, we take responsibility for ensuring the website
        is secure, functional, and compliant with relevant laws and regulations. We welcome your
        feedback and suggestions for improvements and are committed to providing a great user
        experience for all visitors to our site.
      </p>
    </section>

<?php
include("../includes/footer.php");
?>