<?php
$pageTitle = "Prompt Generator Generate | Training Exercises and Assignments";
$pageDescription = "This is the description of my subpage.";
$pageKeywords = "subpage, keywords, SEO";
$pageAuthor = "Joen";
$pageName = "home";
include("../includes/header.php");
?>

<section>
        <h2>About Me</h2>
        <p>Hi there! My name is Joen and I'm a Software Manager. I love creating things and exploring new technologies. That's why I decided to build this website using only ChatGPT's code. Yes, you heard it right, everything you see here is generated by ChatGPT's language model!</p>
        <p>Now, you might be wondering, why did I choose to use ChatGPT to build my website? Well, I believe that AI and natural language processing are going to revolutionize the way we interact with machines and create content. By using ChatGPT, I'm not only showcasing my skills as a developer but also exploring the possibilities of this exciting technology.</p>
        <p>So, feel free to browse around and discover what ChatGPT and I can do for you!</p>
      </section>
      <section>
        <h2>My Services</h2>
        <ul>
          <li>Website development using ChatGPT</li>
          <li>Content creation using ChatGPT</li>
          <li>Consulting on AI and NLP projects</li>
        </ul>
      </section>
      <section>
        <h2>My Portfolio</h2>
        <p>Here are some examples of my work:</p>
        <ul>
          <li><a href="#">Project 1</a></li>
          <li><a href="#">Project 2</a></li>
          <li><a href="#">Project 3</a></li>
        </ul>
      </section>

<?php
include("../includes/footer.php");
?>